### ISSUE TITLE
Amount Format Error while creating from recipe 

### ISSUE THREAD

**Issue by Phlipde** [spliit-app/spliit#140] opened 2024-04-11 18:31 UTC
In the public version, the Amount after scanning is a wrong formatted number.
### After scanning with GPT:
![Screenshot 2024-04-11 200617](https://github.com/spliit-app/spliit/assets/65417693/125a2151-b4ab-4bd3-96c7-e9163d64c855) 
_Example recipe: no real data_
### Real amount (after clicking continue):
![Screenshot 2024-04-11 201148](https://github.com/spliit-app/spliit/assets/65417693/533c2855-21bc-4ea7-8e8d-99d320b7c93b)

The Amount gets rounded and the Cents are not right.
I cannot find out what causes this problem, maybe someone could take a look into it?

The problem could be somewhere around line 201 or in the format Function, which appears to work right in other places in the application. https://github.com/spliit-app/spliit/blob/2fd38aadd91ee5678088b00450b638086307b169/src/app/groups/%5BgroupId%5D/expenses/create-from-receipt-button.tsx#L201

**Comment by mertd** [comment] 2024-09-25 09:52
This may be a duplicate of #87

**Closed** 2024-09-28 22:39 UTC
