### ISSUE TITLE
Allow users to select their UI language

### ISSUE THREAD

**Issue by bohwaz** [spliit-app/spliit#167] opened 2024-06-13 20:47 UTC
My phone is locked in English but I would like to see the UI in French, but the settings of the app don't allow me to change the app language. Please allow us to change the language :) Thanks!

**Comment by bohwaz** [comment] 2024-06-13 21:10
Ah! seeing #75 it seems the app is not available in other languages. Though it's still a good idea to keep this issue for when translations are available :)

**Comment by ChristopherJohnston** [comment] 2024-06-25 08:35
This is enough of a duplicate of #75 to be closed. Any i18n implementation is likely to allow language selection

**Comment by scastiel** [comment] 2024-08-02 15:18
Duplicate of #75

**Closed by scastiel** 2024-08-02 15:18 UTC
